"""
Fluidist Tool (CFD) for Aero-Structural Optimization System

Provides capabilities for 2D aerodynamic analysis of airfoil profiles
using Ansys Fluent via the PyFluent API (ansys-fluent-core).

Prerequisites:
    - A licensed copy of Ansys Fluent installed locally.
    - The AWP_ROOT<ver> environment variable must point to the Ansys installation
      (e.g. AWP_ROOT252 -> C:\\Program Files\\ANSYS Inc\\v252).
      On Windows this is set automatically by the Ansys installer.
    - pip install ansys-fluent-core
"""

import os
import csv

os.environ["ANSYS_NO_WINDOWS_USER_AUTH"] = "1"
os.environ["ANSYSLI_NO_USER_CHECK"] = "1"

import ansys.fluent.core as pyfluent
from ansys.fluent.core import SurfaceDataType


class FluidistAgent:
    """Agent responsible for running 2D aerodynamic analysis via Ansys Fluent."""

    def __init__(self, show_gui: bool = False):
        """
        Launch the Ansys Fluent solver and store the session as self.solver.

        Args:
            show_gui (bool): Set True to open the Fluent GUI for visual debugging.
                             False (default) runs in batch mode — faster for automation.
        """
        print("Launching Ansys Fluent...")

        # We use 2D double-precision ("2ddp") because airfoil boundary layers have
        # very thin, high-gradient regions where single-precision floating point
        # would accumulate error and give us garbage pressure readings.
        #
        # mode: FluentMode.SOLVER launches directly in solver mode (default).
        #       Use FluentMode.MESHING if you need to generate the mesh from scratch.
        # dimension: Dimension.TWO restricts to a 2D plane — our airfoil cross-section.
        # precision: Precision.DOUBLE for 64-bit floats (critical for BL resolution).
        # processor_count: parallelise across 4 CPU cores to speed up the solve.
        # ui_mode: controls whether the Fluent GUI window opens or runs headless.
        self.solver = pyfluent.launch_fluent(
            mode=pyfluent.FluentMode.SOLVER,
            dimension=pyfluent.Dimension.TWO,
            precision=pyfluent.Precision.DOUBLE,
            processor_count=1,
            ui_mode=pyfluent.UIMode.GUI if show_gui else pyfluent.UIMode.NO_GUI,
            additional_arguments="-nwnua",
        )

        # Quick health check — raises if gRPC connection to Fluent is broken.
        assert self.solver.health_check.is_serving, "Fluent session is not healthy!"
        print("Fluent launched successfully.")

        self.show_gui = show_gui

    def generate_or_load_mesh(
        self,
        coords: list,
        dxf_file: str,
        mesh_path: str = "airfoil_2d.msh.h5",
    ):
        """
        Check if a mesh file already exists and load it; otherwise generate
        a new 2D mesh using PyFluent's meshing mode and then load it.

        Args:
            coords (list of tuple): [(x1, y1), ...] in Meters (SI).
            dxf_file (str): Path to .dxf geometry generated by GeometryAgent.
            mesh_path (str): Path to an existing .msh.h5 case file.
        """
        # Store coords for reference — these are the raw (x,y) defining the airfoil profile.
        # All values are in Meters as per SI convention.
        self.coords = coords

        if os.path.exists(mesh_path):
            # If a mesh was already generated (e.g. from a previous run), skip re-meshing.
            # Re-meshing is expensive, so we reuse it when nothing has changed geometrically.
            print(f"Existing mesh found at '{mesh_path}'. Loading...")
        else:
            # No mesh on disk — generate one using the 2D meshing workflow.
            # This launches a *separate* Fluent meshing session. Because Ansys
            # Student licenses strictly allow only ONE concurrent session, we
            # MUST close the current solver session to free the license, run
            # the mesher, and then restart the solver session.
            from physics_cores.ansys_fluent.mesh_airfoil import generate_airfoil_mesh
            import ansys.fluent.core as pyfluent

            print("No mesh found. Temporarily stopping solver to free license for mesher...")
            self.solver.exit()

            print("Generating mesh via Fluent meshing workflow...")
            mesh_path = generate_airfoil_mesh(
                dxf_file=dxf_file,
                output_mesh=mesh_path,
            )

            print(f"Mesh generated at '{mesh_path}'. Restarting solver...")
            self.solver = pyfluent.launch_fluent(
                mode=pyfluent.FluentMode.SOLVER,
                dimension=pyfluent.Dimension.TWO,
                precision=pyfluent.Precision.DOUBLE,
                processor_count=1,
                ui_mode=pyfluent.UIMode.GUI if self.show_gui else pyfluent.UIMode.NO_GUI,
                additional_arguments="-nwnua",
            )

        # Load the mesh into the active solver session.
        self.solver.settings.file.read_case(file_name=mesh_path)

    def set_boundary_conditions(self, inlet_velocity: float = 50.0):
        """
        Configure the physics: set the turbulence model, working fluid, and inlet velocity.

        Args:
            inlet_velocity (float): Freestream velocity at the inlet in m/s (SI). Default 50 m/s.
        """
        # All solver settings are accessed through solver.settings.setup / .solution.
        setup = self.solver.settings.setup

        # ---- Turbulence Model ----
        # k-omega SST (Shear Stress Transport) blends k-omega near the wall and k-epsilon
        # in the freestream. This makes it much better at capturing the flow separation
        # that happens on the airfoil's suction side and near the trailing edge — exactly
        # the regions that drive surface pressure errors.
        # In PyFluent the model is set in two steps: first select k-omega family,
        # then pick the SST variant specifically.
        viscous = setup.models.viscous
        viscous.model = "k-omega"
        viscous.k_omega_model = "sst"
        print("Turbulence model set to k-omega SST.")

        # ---- Working Fluid ----
        # Air at sea-level ISA conditions. Density and viscosity are already set
        # by default in Fluent's material library, so we just reference it.
        setup.materials.fluid["air"]  # ensures air is the active fluid

        # ---- Inlet Boundary Condition ----
        # Zone name "inlet" is hardcoded in both the mesh converter and here.
        # Fluent expects velocity in m/s (SI) by default.
        inlet = setup.boundary_conditions.velocity_inlet["inlet"]
        inlet.momentum.velocity_magnitude.value = inlet_velocity
        print(f"Velocity inlet set to {inlet_velocity} m/s (SI).")

        # ---- Outlet Boundary Condition ----
        # Pressure-outlet with 0 Pa gauge pressure — standard far-field condition.
        # The solver derives the static pressure from the upstream solution; setting
        # gauge = 0 means we let Fluent extrapolate rather than enforcing a value.
        outlet = setup.boundary_conditions.pressure_outlet["outlet"]
        outlet.momentum.gauge_pressure.value = 0.0
        print("Pressure outlet set to 0 Pa gauge.")

        # ---- Symmetry Boundaries ----
        # symmetry_top and symmetry_bottom are typed as "symmetry" in the mesh.
        # Fluent applies the symmetry condition automatically from the zone type;
        # no settings beyond confirming the zones exist are required here.
        setup.boundary_conditions.symmetry["symmetry_top"]
        setup.boundary_conditions.symmetry["symmetry_bottom"]
        print("Symmetry zones confirmed: symmetry_top, symmetry_bottom.")

    def run_simulation(self, iterations: int = 300):
        """
        Initialise the flow field and iterate the solver until convergence.

        Args:
            iterations (int): Maximum number of solver iterations.
                              300 is usually enough for a well-posed 2D RANS case
                              to reach residuals below 1e-5.
        """
        solution = self.solver.settings.solution

        # Hybrid initialisation seeds the velocity and pressure fields with a
        # Laplace equation solve — it converges faster than a simple zero-field start.
        solution.initialization.hybrid_initialize()
        print("Flow field initialised with hybrid method.")

        # Run the coupled pressure-velocity solver for up to `iterations` steps.
        # The solver will write residuals to the console; watch them drop below 1e-4
        # to confirm the solution is converging properly.
        solution.run_calculation.iterate(iter_count=iterations)
        print(f"Solver finished after up to {iterations} iterations.")

    def export_pressure_csv(self, output_path: str = "data/results/pressure_dist.csv"):
        """
        Export the static pressure on the airfoil wall surface to a CSV file.
        This CSV becomes the handoff to the Structuralist FEA tool.

        Uses the fields.field_data API to pull (x, y) face centroids and
        corresponding static pressure values from the "airfoil" wall zone.

        Args:
            output_path (str): Destination path for the pressure CSV (SI: Pascals).
        """
        # Make sure the output directory exists before we try to write to it.
        os.makedirs(os.path.dirname(output_path), exist_ok=True)

        field_data = self.solver.fields.field_data

        # PyFluent 0.20+ removed the class-based request objects
        # (SurfaceFieldDataRequest, ScalarFieldDataRequest) in favour of direct
        # method calls on the field_data object. Both methods return a dict keyed
        # by zone ID (int), not zone name, so we pull the single value with next().

        # Step 1 — Face centroid (x, y, z) coordinates for every face on the
        # airfoil wall. z is always 0 for a 2D mesh; we discard it below.
        centroid_data = field_data.get_surface_data(
            surface_names=["airfoil"],
            data_type=SurfaceDataType.FacesCentroid,
        )
        centroids = next(iter(centroid_data.values()))  # shape Nx3

        # Step 2 — Static (gauge) pressure at each face centroid [Pa].
        # Fluent's internal field name for gauge static pressure is "pressure".
        pressure_data = field_data.get_scalar_field_data(
            field_name="pressure",
            surface_names=["airfoil"],
        )
        pressures = next(iter(pressure_data.values()))  # shape N

        # Step 3 — Write to CSV: columns are x_m, y_m, pressure_Pa (all SI).
        with open(output_path, "w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["x_m", "y_m", "pressure_Pa"])
            for i, p in enumerate(pressures):
                x = float(centroids[i][0])
                y = float(centroids[i][1])
                writer.writerow([x, y, float(p)])

        print(f"Surface pressure exported to '{output_path}' (SI: Pascals).")
        print(f"  → {len(pressures)} data points written.")

    def _check_convergence(
        self,
        mesh_path: str,
        inlet_velocity: float,
        iterations: int,
    ):
        """
        Sample the airfoil pressure field and raise if the solve diverged.

        Divergence heuristics (sufficient, not necessary):
          - Any NaN or Inf pressure value.
          - All pressures exactly zero — indicates hybrid initialisation did not run.
          - max|p| > 1e7 Pa — unphysical for a sub-sonic incompressible case at
            50 m/s (dynamic pressure ~1 530 Pa); the solver blew up rather than
            converging gradually.

        Args:
            mesh_path: Passed through to the error message for Agent 5.
            inlet_velocity: Same — gives Troubleshooter the operating condition.
            iterations: Same — lets Troubleshooter know how many steps were taken.

        Raises:
            RuntimeError: Structured message parseable by the Troubleshooter agent.
        """
        import numpy as np

        field_data = self.solver.fields.field_data
        try:
            pressure_data = field_data.get_scalar_field_data(
                field_name="pressure",
                surface_names=["airfoil"],
            )
            pressures = np.asarray(next(iter(pressure_data.values())), dtype=float)
        except Exception as e:
            raise RuntimeError(
                f"[Fluidist] Could not read pressure after solve — possible divergence. "
                f"mesh={mesh_path!r} velocity={inlet_velocity} m/s "
                f"iterations={iterations} error={e}"
            ) from e

        if pressures.size == 0:
            raise RuntimeError(
                f"[Fluidist] Pressure array is empty — zone 'airfoil' returned no faces. "
                f"mesh={mesh_path!r} velocity={inlet_velocity} m/s"
            )

        if np.any(np.isnan(pressures)) or np.any(np.isinf(pressures)):
            raise RuntimeError(
                f"[Fluidist] Diverged: NaN/Inf pressure values detected. "
                f"mesh={mesh_path!r} velocity={inlet_velocity} m/s "
                f"iterations={iterations}"
            )

        if np.all(pressures == 0.0):
            raise RuntimeError(
                f"[Fluidist] Solve produced all-zero pressure — initialisation may have "
                f"failed silently. "
                f"mesh={mesh_path!r} velocity={inlet_velocity} m/s "
                f"iterations={iterations}"
            )

        max_abs = float(np.max(np.abs(pressures)))
        if max_abs > 1e7:
            raise RuntimeError(
                f"[Fluidist] Diverged: max|pressure| = {max_abs:.2e} Pa exceeds physical "
                f"limit for sub-sonic incompressible flow. "
                f"mesh={mesh_path!r} velocity={inlet_velocity} m/s "
                f"iterations={iterations}"
            )

        print(f"Convergence check passed: max|pressure| = {max_abs:.1f} Pa.")

    def run_from_mesh(
        self,
        mesh_path: str,
        inlet_velocity: float = 50.0,
        iterations: int = 300,
        output_csv: str = "data/results/pressure_dist.csv",
    ) -> str:
        """
        Full CFD pipeline: load mesh → set BCs → solve → export CSV.

        This is the primary entry point for Agent 6 (Lead Orchestrator).
        It chains every step and performs a post-solve divergence check before
        writing the output file, so callers never receive a silently bad CSV.

        Args:
            mesh_path: Path to a valid Fluent ASCII .msh file produced by MeshAgent.
            inlet_velocity: Freestream velocity in m/s (SI). Default 50 m/s.
            iterations: Max solver iterations. 300 is typically enough for 2D RANS
                        to reach residuals below 1e-5 on a clean C-mesh.
            output_csv: Destination path for the pressure distribution CSV.

        Returns:
            Absolute path to the written pressure CSV.

        Raises:
            RuntimeError: If the mesh cannot be loaded or the solve diverges.
                          The message contains mesh, velocity, and iteration count
                          as structured key=value pairs for Agent 5 to parse.
        """
        print(f"[Fluidist] Loading mesh: {mesh_path}")
        try:
            # Fluent 2025 R2+ defaults to CFF/HDF5 mode (.msh.h5). Disable it so
            # Fluent reads our hand-crafted ASCII .msh file as legacy format instead
            # of trying to parse ASCII text as HDF5 binary (which causes SIGSEGV).
            self.solver.tui.file.cff_files("no")
        except Exception:
            pass  # Older PyFluent versions may not expose this TUI path — ignore

        try:
            # solver.settings.file.read_case does not exist in PyFluent 0.20+.
            # Correct paths are solver.file.read_case() (Settings API) or TUI.
            self.solver.tui.file.read_case(mesh_path.replace("\\", "/"))
        except Exception as e:
            raise RuntimeError(
                f"[Fluidist] Failed to load mesh. "
                f"mesh={mesh_path!r} error={e}"
            ) from e

        self.set_boundary_conditions(inlet_velocity=inlet_velocity)

        solution = self.solver.settings.solution
        solution.initialization.hybrid_initialize()
        print("Flow field initialised with hybrid method.")

        solution.run_calculation.iterate(iter_count=iterations)
        print(f"Solver completed up to {iterations} iterations.")

        self._check_convergence(
            mesh_path=mesh_path,
            inlet_velocity=inlet_velocity,
            iterations=iterations,
        )

        self.export_pressure_csv(output_path=output_csv)
        return os.path.abspath(output_csv)

    def close(self):
        """Cleanly shut down the Fluent solver session to free up the license."""
        self.solver.exit()
        print("Fluent session closed.")


# ─── Quick smoke-test when run directly ─────────────────────────────────────
if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--mesh", required=True, help="Path to .msh.h5 file")
    parser.add_argument("--velocity", type=float, default=50.0)
    parser.add_argument("--iterations", type=int, default=300)
    parser.add_argument("--output", default="data/results/pressure_dist.csv")
    args = parser.parse_args()

    agent = FluidistAgent(show_gui=False)
    try:
        agent.run_from_mesh(
            mesh_path=args.mesh,
            inlet_velocity=args.velocity,
            iterations=args.iterations,
            output_csv=args.output,
        )
    finally:
        agent.close()
